### ISSUE TITLE
GitHub tags

### ISSUE THREAD

**Issue by jayvdb** [rsalmaso/django-fluo#1]
The GitHub tags are out of date from the PyPI releases.

Also not uploading sdists to PyPI makes it a bit difficult to do distro packaging, esp when there are no tags here for the latest on PyPI.

**Comment by rsalmaso** [comment]
Hi, tags are ok now (hg-git stopped to push tags :sweat: )
I've pushed a sdist to pypi.

Do you use this package? Because for this particular package I don't care too much about breaking changes and other things (this is a playground of experimental things - and I'm working on 0.5 version which cuts backward compatibility).

**Comment by jayvdb** [comment]
I dont use it directly, and I am guessing that any breaking changes here will be matched with changes in your other fluo packages so I probably wouldnt even notice the breakage ;-)
